spring.application.name=movie-reservation-system
spring.application.name=movie-reservation-system

spring.datasource.url=jdbc:mysql://localhost:3306/movie_reservation_system
spring.datasource.username=root
spring.datasource.password=Prashant19

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
